import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../database/database.dart';
import '../services/shop_services.dart';

class AnalyticsScreen extends StatefulWidget {
  const AnalyticsScreen({super.key});

  @override
  State<AnalyticsScreen> createState() => _AnalyticsScreenState();
}

class _AnalyticsScreenState extends State<AnalyticsScreen> {
  DateTimeRange? _customRange;

  bool _isSameDay(DateTime a, DateTime b) =>
      a.year == b.year && a.month == b.month && a.day == b.day;

  bool _isInRange(DateTime date, DateTime start, DateTime end) {
    final dayOnly = DateTime(date.year, date.month, date.day);
    final startOnly = DateTime(start.year, start.month, start.day);
    final endOnly = DateTime(end.year, end.month, end.day);
    return (dayOnly.isAfter(startOnly) || dayOnly.isAtSameMomentAs(startOnly)) &&
        (dayOnly.isBefore(endOnly) || dayOnly.isAtSameMomentAs(endOnly));
  }

  Future<void> _selectCustomRange(BuildContext context) async {
    final picked = await showDateRangePicker(
      context: context,
      firstDate: DateTime(2020),
      lastDate: DateTime.now(),
      initialDateRange: _customRange ??
          DateTimeRange(
            start: DateTime.now().subtract(const Duration(days: 7)),
            end: DateTime.now(),
          ),
    );
    if (picked != null) setState(() => _customRange = picked);
  }

  Future<void> _generateAndSharePdf({
    required Map<String, double> todayData,
    required Map<String, double> weeklyData,
    required Map<String, double> monthlyData,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Shop Sales Progress & Analytics Report',
                style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Generated on: ${DateTime.now().toLocal().toString().split(".")[0]}',
                style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
              ),
              pw.SizedBox(height: 20),
              pw.TableHelper.fromTextArray(
                headers: ['Period', 'Total Bills', 'Sales Revenue (Rs.)', 'Est. Profit (Rs.)'],
                data: [
                  [
                    "Today's Progress",
                    todayData['count']!.toInt().toString(),
                    todayData['sales']!.toStringAsFixed(2),
                    todayData['profit']!.toStringAsFixed(2),
                  ],
                  [
                    'This Week',
                    weeklyData['count']!.toInt().toString(),
                    weeklyData['sales']!.toStringAsFixed(2),
                    weeklyData['profit']!.toStringAsFixed(2),
                  ],
                  [
                    'This Month',
                    monthlyData['count']!.toInt().toString(),
                    monthlyData['sales']!.toStringAsFixed(2),
                    monthlyData['profit']!.toStringAsFixed(2),
                  ],
                ],
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColor.fromInt(0xFF00796B)),
                cellAlignments: {
                  0: pw.Alignment.centerLeft,
                  1: pw.Alignment.center,
                  2: pw.Alignment.centerRight,
                  3: pw.Alignment.centerRight,
                },
              ),
              pw.SizedBox(height: 30),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Text(
                'Note: This is an automated analytics summary generated by your Shop Management System.',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
              ),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'shop_sales_analytics_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }

  @override
  Widget build(BuildContext context) {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final startOfWeek = today.subtract(Duration(days: now.weekday - 1));
    final startOfMonth = DateTime(now.year, now.month, 1);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Sales Progress & Analytics'),
        actions: [
          IconButton(
            icon: const Icon(Icons.date_range),
            tooltip: 'Select custom date range',
            onPressed: () => _selectCustomRange(context),
          ),
          if (_customRange != null)
            IconButton(
              icon: const Icon(Icons.clear),
              tooltip: 'Clear custom filter',
              onPressed: () => setState(() => _customRange = null),
            ),
          IconButton(
            icon: const Icon(Icons.backup_outlined),
            tooltip: 'Backup database to a JSON file',
            onPressed: () => ShopServices.backupDatabase(context),
          ),
          IconButton(
            icon: const Icon(Icons.restore_outlined),
            tooltip: 'Restore database from a backup file (overwrites current data)',
            onPressed: () async {
              final confirmed = await showDialog<bool>(
                context: context,
                builder: (ctx) => AlertDialog(
                  title: const Text('Restore backup?'),
                  content: const Text(
                      'This replaces ALL current products, bills, and customers with the backup file\'s data. This cannot be undone.'),
                  actions: [
                    TextButton(
                      onPressed: () => Navigator.pop(ctx, false),
                      child: const Text('Cancel'),
                    ),
                    FilledButton(
                      style: FilledButton.styleFrom(backgroundColor: Colors.red),
                      onPressed: () => Navigator.pop(ctx, true),
                      child: const Text('Restore'),
                    ),
                  ],
                ),
              );
              if (confirmed == true && context.mounted) {
                await ShopServices.restoreDatabase(context);
              }
            },
          ),
          const SizedBox(width: 8),
        ],
      ),
      body: StreamBuilder<List<Bill>>(
        stream: db.select(db.bills).watch(),
        builder: (context, billSnapshot) {
          if (billSnapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          final bills = billSnapshot.data ?? [];

          return StreamBuilder<List<BillLine>>(
            stream: db.select(db.billLines).watch(),
            builder: (context, itemSnapshot) {
              final items = itemSnapshot.data ?? [];

              return StreamBuilder<List<Product>>(
                stream: db.watchAllProducts(),
                builder: (context, productSnapshot) {
                  final products = productSnapshot.data ?? [];
                  final productMap = {for (final p in products) p.id: p};

                  Map<String, double> calculateMetrics(List<Bill> targetBills) {
                    double sales = 0.0;
                    double cost = 0.0;
                    for (final bill in targetBills) {
                      final billItemsForBill =
                          items.where((i) => i.billId == bill.id);
                      for (final item in billItemsForBill) {
                        sales += item.unitPrice * item.quantity;
                        final prod = productMap[item.productId];
                        cost += (prod?.purchasePrice ?? 0.0) * item.quantity;
                      }
                    }
                    return {
                      'sales': sales,
                      'profit': sales - cost,
                      'count': targetBills.length.toDouble(),
                    };
                  }

                  final todayBills =
                      bills.where((b) => _isSameDay(b.createdAt, today)).toList();
                  final todayData = calculateMetrics(todayBills);

                  final weeklyBills = bills
                      .where((b) => b.createdAt
                          .isAfter(startOfWeek.subtract(const Duration(seconds: 1))))
                      .toList();
                  final weeklyData = calculateMetrics(weeklyBills);

                  final monthlyBills = bills
                      .where((b) => b.createdAt.isAfter(
                          startOfMonth.subtract(const Duration(seconds: 1))))
                      .toList();
                  final monthlyData = calculateMetrics(monthlyBills);

                  Map<String, double>? customData;
                  if (_customRange != null) {
                    final customBills = bills
                        .where((b) => _isInRange(
                            b.createdAt, _customRange!.start, _customRange!.end))
                        .toList();
                    customData = calculateMetrics(customBills);
                  }

                  final dailyChartData = <Map<String, dynamic>>[];
                  const weekDayNames = [
                    'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'
                  ];
                  for (int i = 6; i >= 0; i--) {
                    final dayDate = today.subtract(Duration(days: i));
                    final dayBills =
                        bills.where((b) => _isSameDay(b.createdAt, dayDate)).toList();
                    final dayMetrics = calculateMetrics(dayBills);
                    final label =
                        i == 0 ? 'Today' : weekDayNames[dayDate.weekday - 1];
                    dailyChartData.add({
                      'label': label,
                      'dateStr': '${dayDate.day}/${dayDate.month}',
                      'sales': dayMetrics['sales']!,
                    });
                  }

                  return SingleChildScrollView(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              'Performance Summary',
                              style: Theme.of(context)
                                  .textTheme
                                  .titleMedium
                                  ?.copyWith(fontWeight: FontWeight.bold),
                            ),
                            ElevatedButton.icon(
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.teal,
                                foregroundColor: Colors.white,
                              ),
                              onPressed: () => _generateAndSharePdf(
                                todayData: todayData,
                                weeklyData: weeklyData,
                                monthlyData: monthlyData,
                              ),
                              icon: const Icon(Icons.share, size: 18),
                              label: const Text('Export / Share PDF'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 16),
                        if (_customRange != null && customData != null) ...[
                          _buildSectionCard(
                            title: 'Custom range',
                            sales: customData['sales']!,
                            profit: customData['profit']!,
                            billCount: customData['count']!.toInt(),
                            accentColor: Colors.purple,
                          ),
                          const SizedBox(height: 24),
                        ],
                        _buildSectionCard(
                          title: "Today's Progress",
                          sales: todayData['sales']!,
                          profit: todayData['profit']!,
                          billCount: todayData['count']!.toInt(),
                          accentColor: Colors.teal,
                        ),
                        const SizedBox(height: 16),
                        _buildSectionCard(
                          title: 'This Week',
                          sales: weeklyData['sales']!,
                          profit: weeklyData['profit']!,
                          billCount: weeklyData['count']!.toInt(),
                          accentColor: Colors.indigo,
                        ),
                        const SizedBox(height: 16),
                        _buildSectionCard(
                          title: 'This Month',
                          sales: monthlyData['sales']!,
                          profit: monthlyData['profit']!,
                          billCount: monthlyData['count']!.toInt(),
                          accentColor: Colors.deepOrange,
                        ),
                        const SizedBox(height: 28),
                        Text(
                          'Daily Sales Trend (Last 7 Days)',
                          style: Theme.of(context)
                              .textTheme
                              .titleMedium
                              ?.copyWith(fontWeight: FontWeight.bold),
                        ),
                        const SizedBox(height: 12),
                        _buildDailySalesChart(dailyChartData),
                      ],
                    ),
                  );
                },
              );
            },
          );
        },
      ),
    );
  }

  Widget _buildSectionCard({
    required String title,
    required double sales,
    required double profit,
    required int billCount,
    required Color accentColor,
  }) {
    final avgBill = billCount > 0 ? sales / billCount : 0.0;
    return Card(
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(color: accentColor.withValues(alpha: 0.3)),
      ),
      color: accentColor.withValues(alpha: 0.04),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(title,
                    style: const TextStyle(
                        fontSize: 16, fontWeight: FontWeight.bold)),
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: accentColor.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text('$billCount bills',
                      style: const TextStyle(
                          fontSize: 12, fontWeight: FontWeight.w600)),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                _buildMetricBox('Sales Revenue', 'Rs. ${sales.toStringAsFixed(2)}',
                    null, Colors.green.shade800),
                const SizedBox(width: 12),
                _buildMetricBox(
                    'Estimated Profit',
                    'Rs. ${profit.toStringAsFixed(2)}',
                    Icons.trending_up,
                    profit >= 0 ? Colors.teal.shade800 : Colors.red),
                const SizedBox(width: 12),
                _buildMetricBox('Average Order', 'Rs. ${avgBill.toStringAsFixed(2)}',
                    Icons.shopping_bag_outlined, Colors.blueGrey.shade800),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildMetricBox(String label, String value, IconData? icon, Color color) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(color: Colors.grey.shade300),
        ),
        child: Row(
          children: [
            if (icon != null) ...[Icon(icon, size: 22, color: color), const SizedBox(width: 8)],
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(label,
                      style: const TextStyle(fontSize: 11, fontWeight: FontWeight.w500, color: Colors.black54)),
                  const SizedBox(height: 2),
                  Text(value,
                      style: const TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: Colors.black87),
                      overflow: TextOverflow.ellipsis),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildDailySalesChart(List<Map<String, dynamic>> chartData) {
    double maxSales = 0.0;
    for (final day in chartData) {
      if ((day['sales'] as double) > maxSales) maxSales = day['sales'] as double;
    }
    if (maxSales == 0) maxSales = 100.0;

    return Card(
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(color: Colors.teal.shade200),
      ),
      child: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Row(
              children: [
                Icon(Icons.bar_chart, color: Colors.teal),
                SizedBox(width: 8),
                Text('Sales Revenue Comparison',
                    style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
              ],
            ),
            const SizedBox(height: 20),
            SizedBox(
              height: 220,
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: chartData.map((day) {
                  final sales = day['sales'] as double;
                  final heightRatio = (sales / maxSales).clamp(0.05, 1.0);
                  final isHighest = sales > 0 && sales == maxSales;
                  return Column(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      Text(sales > 0 ? 'Rs. ${sales.toStringAsFixed(0)}' : '0',
                          style: const TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                      const SizedBox(height: 4),
                      AnimatedContainer(
                        duration: const Duration(milliseconds: 300),
                        width: 36,
                        height: 130 * heightRatio,
                        decoration: BoxDecoration(
                          color: isHighest ? Colors.teal : Colors.teal.shade200,
                          borderRadius:
                              const BorderRadius.vertical(top: Radius.circular(6)),
                        ),
                      ),
                      const SizedBox(height: 6),
                      Text(day['label'] as String,
                          style:
                              const TextStyle(fontSize: 12, fontWeight: FontWeight.w600)),
                      Text(day['dateStr'] as String,
                          style: const TextStyle(fontSize: 10)),
                    ],
                  );
                }).toList(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}


